### ISSUE TITLE
Dead urls

### ISSUE THREAD

**Issue by StephanStanisic** [os-js/OS.js-extras#6]
The manual pages are just redirecting to the documentation's homepage, not to the desired manual page.

<https://os-js.org/doc/manuals/man-google-api.html>  
<https://os-js.org/doc/manuals/man-zip.html>

**Comment by andersevenrud** [comment]
@StephanStanisic Hi.

Thanks for reporting. I'm in the process of making a new maual, so I'll have this fixed ASAP :)
