### ISSUE TITLE
Having trouble running extras (specifically AceEditor) on Raspberry Pi

### ISSUE THREAD

**Issue by alimohamad** [os-js/OS.js-extras#7]
After running the install for the extras package as described on the page, I was able to see the icon, and execute it, but then I got this error message (an error window launched):

```
Error: Application 'ApplicationAceEditor' preloading failed: 
/packages/extras/AceEditor/ace/ace.js,/packages/extras/AceEditor/main.js,/packages/extras/AceEditor/main.css

```

I also got this from tracing:

```
Error: Application 'ApplicationAceEditor' preloading failed: 
/packages/extras/AceEditor/ace/ace.js,/packages/extras/AceEditor/main.js,/packages/extras/AceEditor/main.css
    at a (http://192.168.1.27:8000/osjs.js:31:79946)
    at http://192.168.1.27:8000/osjs.js:31:80035
    at o (http://192.168.1.27:8000/common.js:55:72338)
    at o._settlePromiseFromHandler (http://192.168.1.27:8000/common.js:55:45904)
    at o._settlePromise (http://192.168.1.27:8000/common.js:55:46704)
    at o._settlePromise0 (http://192.168.1.27:8000/common.js:55:47403)
    at o._settlePromises (http://192.168.1.27:8000/common.js:55:48730)
    at http://192.168.1.27:8000/common.js:55:2629
    at <anonymous>
From previous event:
    at o.v [as _captureStackTrace] (http://192.168.1.27:8000/common.js:55:10242)
    at o._resolveFromExecutor (http://192.168.1.27:8000/common.js:55:45444)
    at new o (http://192.168.1.27:8000/common.js:55:37727)
    at Function.value (http://192.168.1.27:8000/osjs.js:31:80575)
    at Array.<anonymous> (http://192.168.1.27:8000/packages/default/CoreWM/main.js:31:60881)
    at http://192.168.1.27:8000/osjs.js:31:99911
    at r (http://192.168.1.27:8000/osjs.js:31:98888)
    at HTMLElement.<anonymous> (http://192.168.1.27:8000/osjs.js:31:99821)
    at HTMLElement.<anonymous> (http://192.168.1.27:8000/osjs.js:31:17432)

```

I peeked around old issues that were closed, and noticed it was also prevalent in Arduino Yun and Tian boards. Is there a fix?

**Comment by andersevenrud** [comment]
Can you send me the `dist/packages/extras/AceEditor` directory ?

**Comment by alimohamad** [comment]
Hm, the directory doesn't exist - I double checked if I had installed it, and it said "repo has already been installed" when I tried installing it again. However, I've been having this issue with Xterm and the default apps as well.

**Comment by andersevenrud** [comment]
If you used `bin/add-package-repo.sh` there was a bug that [possibly] prevented building. Do a `node osjs build:packages` to rebuild manually.

This script will not proceed to build if the `src/packages` directory already exists.

**Comment by andersevenrud** [comment]
> This script will not proceed to build if the src/packages directory already exists.

This should probably not happen, come to think of it. It would be better if it just "dumbly" proceeded with installation as default, even though it is already installed.

**Comment by andersevenrud** [comment]
If it still fails after that, I'm assuming something went wrong with that package spesifically.

I'd suggest you try:

```
cd src/packages/extras/AceEditor
npm install
```

Then go back to OS.js main directory and do: `node osjs build:package --name=extras/AceEditor`

and keep an eye out for errors.

**Comment by alimohamad** [comment]
I did in fact use the ```bin/add-package-repo.sh commands```, that explains it. However, I just ran ```node osjs build:packages``` and got this nasty looking error:

```
ERROR in ./main.less
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './node_modules/xterm/dist/xterm.css' in '/home/alimo/Documents/OS.js/src/packages/xterm/Xterm'
    at factoryCallback (/home/alimo/Documents/OS.js/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/home/alimo/Documents/OS.js/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/home/alimo/Documents/OS.js/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/home/alimo/Documents/OS.js/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /home/alimo/Documents/OS.js/node_modules/webpack/node_modules/async/dist/async.js:3861:9
    at /home/alimo/Documents/OS.js/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/alimo/Documents/OS.js/node_modules/webpack/node_modules/async/dist/async.js:996:13)
    at /home/alimo/Documents/OS.js/node_modules/webpack/node_modules/async/dist/async.js:906:16
    at /home/alimo/Documents/OS.js/node_modules/webpack/node_modules/async/dist/async.js:3858:13
    at resolvers.normal.resolve (/home/alimo/Documents/OS.js/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/alimo/Documents/OS.js/node_modules/tapable/lib/Tapable.js:252:11)
    at /home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/alimo/Documents/OS.js/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/alimo/Documents/OS.js/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/Resolver.js:168:10)
    at loggingCallbackWrapper (/home/alimo/Documents/OS.js/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/alimo/Documents/OS.js/node_modules/tapable/lib/Tapable.js:252:11)
 @ ./main.less
 @ multi main.js main.less

ERROR in /home/alimo/Documents/OS.js/node_modules/css-loader?{"sourceMap":true,"minimize":true}!/home/alimo/Documents/OS.js/node_modules/less-loader/dist/cjs.js?{"paths":["/home/alimo/Documents/OS.js/src/client/stylesheets"],"sourceMap":true}!./main.less
Module not found: Error: Can't resolve './node_modules/xterm/dist/xterm.css' in '/home/alimo/Documents/OS.js/src/packages/xterm/Xterm'
 @ /home/alimo/Documents/OS.js/node_modules/css-loader?{"sourceMap":true,"minimize":true}!/home/alimo/Documents/OS.js/node_modules/less-loader/dist/cjs.js?{"paths":["/home/alimo/Documents/OS.js/src/client/stylesheets"],"sourceMap":true}!./main.less 3:10-142
 @ ./main.less
 @ multi main.js main.less

ERROR in ./main.js
Module not found: Error: Can't resolve 'xterm' in '/home/alimo/Documents/OS.js/src/packages/xterm/Xterm'
 @ ./main.js 7:13-29
 @ multi main.js main.less
Child extract-text-webpack-plugin ../../../../node_modules/extract-text-webpack-plugin/dist ../../../../node_modules/css-loader/index.js??ref--5-2!../../../../node_modules/less-loader/dist/cjs.js??ref--5-3!main.less:
       [0] /home/alimo/Documents/OS.js/node_modules/css-loader?{"sourceMap":true,"minimize":true}!/home/alimo/Documents/OS.js/node_modules/less-loader/dist/cjs.js?{"paths":["/home/alimo/Documents/OS.js/src/client/stylesheets"],"sourceMap":true}!./main.less 6.79 kB {0} [built]
        + 1 hidden module
    
    ERROR in /home/alimo/Documents/OS.js/node_modules/css-loader?{"sourceMap":true,"minimize":true}!/home/alimo/Documents/OS.js/node_modules/less-loader/dist/cjs.js?{"paths":["/home/alimo/Documents/OS.js/src/client/stylesheets"],"sourceMap":true}!./main.less
    Module not found: Error: Can't resolve './node_modules/xterm/dist/xterm.css' in '/home/alimo/Documents/OS.js/src/packages/xterm/Xterm'
     @ /home/alimo/Documents/OS.js/node_modules/css-loader?{"sourceMap":true,"minimize":true}!/home/alimo/Documents/OS.js/node_modules/less-loader/dist/cjs.js?{"paths":["/home/alimo/Documents/OS.js/src/client/stylesheets"],"sourceMap":true}!./main.less 3:10-142
Error: Command failed: /home/alimo/Documents/OS.js/node_modules/.bin/webpack
    at checkExecSyncError (child_process.js:592:13)
    at execSync (child_process.js:632:13)
    at Promise (/home/alimo/Documents/OS.js/node_modules/ygor/index.js:70:13)
    at new Promise (<anonymous>)
    at Function.shell (/home/alimo/Documents/OS.js/node_modules/ygor/index.js:68:10)
    at Object.execWebpack (/home/alimo/Documents/OS.js/node_modules/osjs-build/utils.js:169:15)
    at getPackageMetadata.then (/home/alimo/Documents/OS.js/node_modules/osjs-build/packages.js:246:12)
    at <anonymous>

```

Although this message is also for Xterm and not the extras package, so I'm not really sure what to do.

**Comment by andersevenrud** [comment]
```
Module not found: Error: Can't resolve 'xterm' in '/home/alimo/Documents/OS.js/src/packages/xterm/Xterm'
```

This is the part of the error that is important. Run `npm install` in the package directory.

**Comment by andersevenrud** [comment]
I'm going to assume that the add script failed here :/ I'll have to make some improvements to this.

**Comment by andersevenrud** [comment]
The script basically does:

1. Clone the Github repository
2. Go into each package and run `npm install`
3. Run `node osjs config:add --name=repositories --value=<repo name>`
4. Run `node osjs build:manifest`
5. Run `node osjs build:packages --repositories=<repo name>`

And it most likely failed silently on step 2. (Step 5 was where the bug I mentioned *was*).

**Comment by alimohamad** [comment]
Ohh ok! I'm running through all of the steps now. Going to focus on Xterm and Ace because those are really the only two that I need for what I'm trying to accomplish (basically trying to create a lightweight version of Raspbian that runs OS.js on bootup and lets you develop directly on the Pi without plugging in a mouse, keyboard, or display port)

**Comment by andersevenrud** [comment]
Cool! Let me know how it works out with the installation :)

**Comment by alimohamad** [comment]
Will do. So to recap, I basically just have to: 

1. Go into the directory for each package (in the src or dist directory?) 
2. Run ```npm install```
3. Go back to the top directory
4.Run the config command
5. Build the manifest
6. Build the package?

**Comment by andersevenrud** [comment]
1. You only need to do this for Xterm and AceEditor I believe
2. Yes
3. You can skip this this step was done at your first attempt (since you can see the packages in OS.js)
4. Same as above
5. Yes, ex `node osjs build:package --name=extras/AceEditor`

**Comment by alimohamad** [comment]
Cool, and this is in the src directory right?

**Comment by andersevenrud** [comment]
Like this:
```
anders@andersarch:~/Projects/OS.js (development)*$ cd src/packages/xterm/Xterm/
anders@andersarch:~/Projects/OS.js/src/packages/xterm/Xterm (master)*$ npm install

# ... snip ...

anders@andersarch:~/Projects/OS.js/src/packages/xterm/Xterm (master)*$ cd ../../../../
anders@andersarch:~/Projects/OS.js (development)*$ node osjs build:package --name=xterm/Xterm

Building xterm/Xterm
# ... snip ...
```

**Comment by andersevenrud** [comment]
Regarding these two commands:

1. `node osjs config:set --name=repositories --value=` This adds a `src/package` directory into the registry so that it becomes visible/available to the build system.
2. `node osjs build:manifest` Builds a package manifest of *everything*  in `src/packages`. This is what the client will use to populate its PackageManager (which in turns makes them visible in menu)

**Comment by andersevenrud** [comment]
Regarding these two commands:

1. `node osjs config:set --name=repositories --value=` This adds a `src/package` directory into the registry so that it becomes visible/available to the build system.
2. `node osjs build:manifest` Builds a package manifest of *everything* (well, the repositories configured with above command)  in `src/packages`. This is what the client will use to populate its PackageManager (which in turns makes them visible in menu)

**Comment by alimohamad** [comment]
Ohhhh that makes sense now (I'm kind of a beginner, a lot of this stuff was way above my knowledge base. Thanks for explaining it!)

Good news is the apps run now, which is great! Xterm is giving me this error inside the terminal though:

```
ssh: connect to host localhost port 22: Connection refused
```
I'm guessing this is an Xterm issue though. Thank you so much!

**Comment by andersevenrud** [comment]
> ssh: connect to host localhost port 22: Connection refused

You probably don't have sshd running (or it is blocked in firewall) :)

**Comment by andersevenrud** [comment]
Some notes about the Xterm client:

* It runs over ssh
* Requires bash

So you'll need both of those.

Also, you should use `pam` or `shadow` authentication on OS.js, because currently the app takes the session username and tries to connect with that (which is *demo* by default). I'm not quite finished with this app yet.

**Comment by alimohamad** [comment]
I already have ssh and bash running on my Pi - is there anything else I should do to get it to run?

**Comment by andersevenrud** [comment]
No, those are the only requirements. You've probably used SSH to install OS.js, right ?

**Comment by alimohamad** [comment]
I've actually been doing all this by developing directly onto the Pi - I tried ssh'ing into it from another system and I got the same error. Thanks for the tip.

**Comment by andersevenrud** [comment]
> Also, you should use pam or shadow authentication on OS.js, because currently the app takes the session username and tries to connect with that (which is demo by default)

I just pushed an update to the package, so if that you're in demo mode, you'll get asked to enter a username to use for the SSH connection. I should have done this a long time ago, really.

> I've actually been doing all this by developing directly onto the Pi - I tried ssh'ing into it from another system and I got the same error. Thanks for the tip.

RasPi comes with ssh disabled by default as far as I know (same with Ubuntu).

**Comment by andersevenrud** [comment]
Btw. If you feel Issues are hard to communicate with, I do have a chat support page: https://gitter.im/os-js/OS.js

**Comment by alimohamad** [comment]
Just joined the support page - is there anywhere in specific I should go to continue getting help on this issue? (also, I turned SSH on on my Pi, it wants a password for demo@localhost - I'm guessing if I install the package you just pushed, that will be different.)

**Comment by andersevenrud** [comment]
>  (also, I turned SSH on on my Pi, it wants a password for demo@localhost - I'm guessing if I install the package you just pushed, that will be different.)

Yes, do a `git pull` inside the `src/packages/xterm` directory. Then rebuild the package and restart OS.js server.

Just Say `Hello @andersevenrud` or something :P

**Comment by andersevenrud** [comment]
I'm closing this issue now, because I'm pretty sure everything works fine now. I'll handle the add-package script in the main repo.

**Comment by andersevenrud** [comment]
Ops! I forgot something in my update, make sure to pull again if you haven't already!

**Comment by alimohamad** [comment]
Got a ```TypeError: Cannot read property 'split' of undefined``` - guessing this is what you forgot?

**Comment by andersevenrud** [comment]
Might have caused that error, yes.

**Comment by alimohamad** [comment]
Hm, I just tried pulling again, and it said it was up-to-date.(Sorry for taking up so much of your time btw, I understand this is super specific to me.) Is there a default password for demo@localhost?

**Comment by andersevenrud** [comment]
Well, then you have the latest version. Btw, by default OS.js runs without extended debugging, so when you rebuild a package you have to restart the server, and reload the app in your browser. Also, this might cause your browser to cache old code. So you might have to clear your cache (or use `CTRL+ALT+R` for "hard refresh"). This is what the `--debug` flag is for (as noted in documentation).

> Is there a default password for demo@localhost?

I think you misunderstand. The OS.js Xterm client opens up a SSH connection to *localhost*, which in this case is your Pi. You probably don't have a "demo" user there... you want to use your own, or root, or whatever.

The change I made creates a popup, so you yourself can choose (when running in demo mode).

**Comment by andersevenrud** [comment]
You can confirm you have the latest version by using `git log` and comparing it to https://github.com/os-js/osjs-xterm/commits/master .
